# Generated by Django 2.1.5 on 2019-01-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
