# Generated by Django 2.1.5 on 2019-01-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='status',
            field=models.CharField(db_index=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='send',
            name='code',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
