# Generated by Django 2.1.5 on 2019-01-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190120_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
