# Generated by Django 2.1.5 on 2019-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_send_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='error',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
