# Generated by Django 2.1.5 on 2019-01-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_send_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
