# Generated by Django 2.1.5 on 2019-01-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20190122_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AddField(
            model_name='test',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
