# Generated by Django 2.1.5 on 2019-01-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20190123_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='send',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.RemoveField(
            model_name='test',
            name='date_pub',
        ),
        migrations.AddField(
            model_name='send',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
