# Generated by Django 2.1.5 on 2019-01-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20190123_0549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='send',
            options={},
        ),
        migrations.RemoveField(
            model_name='send',
            name='date_pub',
        ),
    ]
