# Generated by Django 2.1.4 on 2019-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='rescompil',
            field=models.CharField(db_index=True, default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='resrun',
            field=models.CharField(db_index=True, default=' ', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
