# Generated by Django 2.1.4 on 2019-01-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_auto_20190113_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='rescompil',
            new_name='rescomp',
        ),
    ]
