# Generated by Django 2.1.4 on 2019-01-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_auto_20190113_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='rescomp',
            field=models.CharField(blank=True, db_index=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='solution',
            name='resrun',
            field=models.CharField(blank=True, db_index=True, max_length=1500),
        ),
    ]
