# Generated by Django 2.1.4 on 2019-01-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_auto_20190113_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True, db_index=True, max_length=5000),
        ),
    ]
