# Generated by Django 2.1.5 on 2019-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0007_auto_20190113_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='input',
            field=models.TextField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='rescomp',
            field=models.CharField(blank=True, db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='resrun',
            field=models.CharField(blank=True, db_index=True, max_length=2000),
        ),
    ]
